# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "front/"
  publish = "dist/"
  command = "npm run generate"

[[redirects]]
  from = "https://gisyohub.netlify.com/"
  to = "https://gisyohub.com/"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://gisyohub.herokuapp.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/sessions/*"
  to = "https://gisyohub.herokuapp.com/sessions/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/auth/*"
  to = "https://gisyohub.herokuapp.com/auth/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
