[build]
  base = "front"
  publish = "dist"
  command = "yarn build"
[[redirects]]
  from = "/api"
  to = "http://api.gisyohub.com/api"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/auth"
  to = "http://api.gisyohub.com/auth"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/sessions"
  to = "http://api.gisyohub.com/sessions"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
