version: '2'
services:
  data:
    image: busybox
    command: /bin/sh
    volumes:
      - /share
      - ../rails:/rails
      - ../front:/front
      - ../log:/log
      - ../db:/db
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./mysql/app.conf:/etc/mysql/conf.d/app.conf:ro
  db:
    image: mysql:5
    environment: 
      MYSQL_DATABASE: $PROJECT_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      PGDATA: /db/mysql/data
    volumes_from:
      - data
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    depends_on: 
      - rails
      - front
    ports:
     - "80:${WEB_PORT}"
     - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - PORT=$WEB_PORT
      - RAILS_PORT
      - NODE_PORT
      - NODE_ENV=development
  rails:
    build:
      context: ../rails
      dockerfile: docker/Dockerfile.test
      args:
        - RUBY_VERSION
    working_dir: /rails
    depends_on:
      - db
    ports:
      - $RAILS_PORT:$RAILS_PORT
    volumes_from:
      - data
    environment:
      - PORT=$RAILS_PORT
      - RAILS_ENV=development
      - SECRET_KEY_BASE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - TWITTER_KEY
      - TWITTER_SECRET
  front:
    build:
      context: ../front
      dockerfile: docker/Dockerfile
    working_dir: /front
    ports:
     - $NODE_PORT:$NODE_PORT
    volumes_from:
      - data
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=$NODE_PORT
      - API_PORT=$WEB_PORT
