version: '2'
services:
  data:
    image: busybox
    command: /bin/sh
    volumes:
      - /share
      - ../rails:/rails
      - ../front:/front
      - ../log:/log
      - ../db:/db
      - ./nginx_dev/app.conf:/etc/nginx/conf.d/app.conf
      - ./mysql/app.conf:/etc/mysql/conf.d/app.conf:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    user: ${USER_ID}:${GROUP_ID}
  db:
    image: mysql:5
    environment: 
      MYSQL_DATABASE: $PROJECT_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      PGDATA: /app/db/mysql/data
    volumes_from:
      - data
  nginx_dev:
    image: nginx
    ports:
     - "80:${WEB_PORT}"
     - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - ./nginx_dev:/nginx
      - ../front:/front
      - ../log:/log
    depends_on: 
      - rails
      - front
    environment: 
      RAILS_PORT: $RAILS_PORT
      NODE_PORT: $NODE_PORT
    command: /bin/bash /nginx/start.sh
  rails:
    build:
      context: ../rails
      dockerfile: docker/Dockerfile
    environment:
      - RAILS_ENV
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - TWITTER_KEY
      - TWITTER_SECRET
    depends_on: 
      - data
      - db
    volumes_from:
      - data
    ports:
      - $RAILS_PORT:$RAILS_PORT
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /rails
  front:
    build:
      context: ../front
      dockerfile: docker/Dockerfile
    volumes_from:
      - data
    ports:
     - $NODE_PORT:$NODE_PORT
    environment:
      NODE_ENV: $NODE_ENV
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: $NODE_PORT
      API_PORT: $WEB_PORT
    user: ${USER_ID}:${GROUP_ID}
