version: '2'
services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    depends_on: 
      - rails
    ports:
     - "80:${PORT}"
    environment:
      - PORT
      - RAILS_PORT
      - NODE_PORT
      - NODE_ENV=production
  rails:
    image: registry.heroku.com/gisyohub/rails
    build:
      context: ../rails
      dockerfile: docker/Dockerfile.production
      args:
        - RUBY_VERSION
    ports:
      - $RAILS_PORT:$RAILS_PORT
    working_dir: /rails
    environment:
      - PORT
      - RAILS_ENV=production
      - SECRET_KEY_BASE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - TWITTER_KEY
      - TWITTER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_SECRET
  # front container just to BUILD contents. this container has no server capability.
  front:
    build:
      context: ../front
      dockerfile: docker/Dockerfile
    ports:
     - $NODE_PORT:$NODE_PORT
    working_dir: /front
    volumes:
      - ../front:/front
    environment:
      - NODE_ENV=production
      - API_HOST=gisyohub.com
      - API_PORT=$WEB_PORT
      - PORT
