version: '2'
services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    depends_on: 
      - rails
    network_mode: "host"
    ports:
     - "80:${WEB_PORT}"
    environment:
      - PORT=$WEB_PORT
      - RAILS_PORT
      - NODE_PORT
      - NODE_ENV=production
  rails:
    build:
      context: ../rails
      dockerfile: docker/Dockerfile.production
      args:
        - RUBY_VERSION
    working_dir: /rails
    network_mode: "host"
    ports:
      - $RAILS_PORT:$RAILS_PORT
    environment:
      - PORT=$RAILS_PORT
      - RAILS_ENV=production
      - SECRET_KEY_BASE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - TWITTER_KEY
      - TWITTER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_SECRET
  # we do not use front container since nginx provides pre-compiled contents from front directory.
