default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch("DB_USER") %> { 'postgres' } 
  password: <%= ENV.fetch("DB_PASSWORD") %> { '' }
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'gishohub' } %>_dev

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'gishohub' } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'gishohub' } %>_production
