default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>
  username: <%= ENV.fetch("DB_USER") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'gishohub' } %>_dev

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'gishohub' } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'gishohub_dev' } %>_production
