name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      RAILS_PORT: 3000
      NODE_PORT: 3010
      WEB_PORT: 1080
      DB_HOST: db
      DB_NAME: gisyohub
      DB_USER: root
      DB_PASSWORD: ""
      PROJECT_NAME: gisyohub
      SECRET_KEY_BASE: xxxxx
      COMPOSE_PROJECT_NAME: gisyohub_ci
      COMPOSE_FILE: docker/docker-compose.development.yml
      TWITTER_KEY: "DUMMY_TWITTER_KEY"
      TWITTER_SECRET: "DUMMY_TWITTER_SECRET"
      TWITTER_ACCESS_TOKEN: "DUMMY_TWITTER_ACCESS_TOKEN"
      TWITTER_ACCESS_SECRET: "DUMMY_TWITTER_ACCESS_SECRET"
      USER_ID: 0
      GROUP_ID: 0

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose build
    - name: start docker db container
      run: docker-compose up -d db
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: start docker rails container
      run: docker-compose up -d rails
    - name: Check running containers
      run: docker ps
    - name: Run test suite
      run: docker exec rails spec
